package com.yosnowmow.model;

import com.google.cloud.Timestamp;

import java.util.List;

/**
 * Represents a document in the Firestore {@code disputes/{disputeId}} collection.
 *
 * A dispute is created when a Requester opens a claim against a completed or
 * incomplete job within the 2-hour dispute window.  An Admin adjudicates and
 * records the resolution outcome here.
 *
 * The job document stores a {@code disputeId} back-reference once the dispute
 * is opened.
 *
 * Status values:
 *   OPEN     — dispute has been filed; awaiting admin review
 *   RESOLVED — admin has adjudicated; payment action has been taken
 *
 * Resolution values (set only when status = RESOLVED):
 *   RELEASED — full payment released to Worker
 *   REFUNDED — full refund issued to Requester
 *   SPLIT    — partial payout to Worker, partial refund to Requester
 */
public class Dispute {

    // ── Identity ─────────────────────────────────────────────────────────────

    /** UUID v4 generated by DisputeService when the dispute is opened. */
    private String disputeId;

    /** Firestore ID of the job this dispute is about. */
    private String jobId;

    /** Firebase UID of the user who opened the dispute (always the Requester). */
    private String openedByUid;

    /** Timestamp when the dispute was opened. */
    private Timestamp openedAt;

    // ── State ─────────────────────────────────────────────────────────────────

    /**
     * Current dispute status.
     * Valid values: OPEN | RESOLVED
     */
    private String status;

    /**
     * Admin's resolution decision.
     * Valid values: RELEASED | REFUNDED | SPLIT
     * Null until status = RESOLVED.
     */
    private String resolution;

    /**
     * Percentage of the worker's standard payout to transfer on a SPLIT resolution.
     * Range: 0–100.  Ignored for RELEASED/REFUNDED resolutions.
     */
    private int splitPercentageToWorker;

    // ── Statements ────────────────────────────────────────────────────────────

    /** The Requester's account of what happened (required to open the dispute). */
    private String requesterStatement;

    /**
     * The Worker's response statement.
     * Null until the Worker submits a statement via
     * {@code POST /api/disputes/{disputeId}/statement}.
     */
    private String workerStatement;

    // ── Evidence ──────────────────────────────────────────────────────────────

    /**
     * Firebase Storage URLs for uploaded evidence files.
     * Populated by P2-02 (evidence upload).
     * Initialized to an empty list on creation.
     */
    private List<String> evidenceUrls;

    // ── Admin adjudication ────────────────────────────────────────────────────

    /** Admin's notes explaining the resolution rationale. */
    private String adminNotes;

    /** Firebase UID of the admin who resolved this dispute. */
    private String resolvedByAdminUid;

    /** Timestamp when the admin resolved the dispute. */
    private Timestamp resolvedAt;

    // ── Constructor ───────────────────────────────────────────────────────────

    /** Required by Firestore deserialisation. */
    public Dispute() {}

    // ── Getters & Setters ─────────────────────────────────────────────────────

    public String getDisputeId() { return disputeId; }
    public void setDisputeId(String disputeId) { this.disputeId = disputeId; }

    public String getJobId() { return jobId; }
    public void setJobId(String jobId) { this.jobId = jobId; }

    public String getOpenedByUid() { return openedByUid; }
    public void setOpenedByUid(String openedByUid) { this.openedByUid = openedByUid; }

    public Timestamp getOpenedAt() { return openedAt; }
    public void setOpenedAt(Timestamp openedAt) { this.openedAt = openedAt; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getResolution() { return resolution; }
    public void setResolution(String resolution) { this.resolution = resolution; }

    public int getSplitPercentageToWorker() { return splitPercentageToWorker; }
    public void setSplitPercentageToWorker(int splitPercentageToWorker) {
        this.splitPercentageToWorker = splitPercentageToWorker;
    }

    public String getRequesterStatement() { return requesterStatement; }
    public void setRequesterStatement(String requesterStatement) {
        this.requesterStatement = requesterStatement;
    }

    public String getWorkerStatement() { return workerStatement; }
    public void setWorkerStatement(String workerStatement) {
        this.workerStatement = workerStatement;
    }

    public List<String> getEvidenceUrls() { return evidenceUrls; }
    public void setEvidenceUrls(List<String> evidenceUrls) { this.evidenceUrls = evidenceUrls; }

    public String getAdminNotes() { return adminNotes; }
    public void setAdminNotes(String adminNotes) { this.adminNotes = adminNotes; }

    public String getResolvedByAdminUid() { return resolvedByAdminUid; }
    public void setResolvedByAdminUid(String resolvedByAdminUid) {
        this.resolvedByAdminUid = resolvedByAdminUid;
    }

    public Timestamp getResolvedAt() { return resolvedAt; }
    public void setResolvedAt(Timestamp resolvedAt) { this.resolvedAt = resolvedAt; }
}
