package com.yosnowmow.model;

import com.google.cloud.Timestamp;
import com.google.cloud.firestore.GeoPoint;

import java.util.List;

/**
 * Represents a document from the Firestore {@code jobs/{jobId}} collection.
 *
 * All pricing amounts are in CAD (not cents) as decimals, matching the spec §3.2
 * field names (tierPriceCAD, hstAmountCAD, etc.).  The implementation plan
 * draft used integer cents; the spec is the authoritative source.
 *
 * Pricing fields are null at creation — they are set when the Worker accepts
 * the job and locked at CONFIRMED.
 *
 * All fields match spec §3.2 exactly.  Fields used only in Phase 2/3 are
 * included as stubs so the document schema remains stable.
 */
public class Job {

    // ── Identity ─────────────────────────────────────────────────────────────

    /** UUID v4 generated by the backend (not Firestore auto-ID). */
    private String jobId;

    private String requesterId;

    /** Null until a Worker accepts. */
    private String workerId;

    /**
     * Job lifecycle state.
     * Valid values: POSTED, NEGOTIATING, AGREED, ESCROW_HELD, IN_PROGRESS,
     *               PENDING_APPROVAL, INCOMPLETE, DISPUTED, RELEASED, REFUNDED,
     *               SETTLED, CANCELLED
     */
    private String status;

    // ── Scope & Location ─────────────────────────────────────────────────────

    /**
     * What needs to be cleared — subset of ["driveway", "sidewalk", "both"].
     * "both" means driveway + front and side walks.
     */
    private List<String> scope;

    /**
     * Property address — private until job reaches CONFIRMED status.
     * The GET /jobs/{id} endpoint omits this field for Workers until confirmed.
     */
    private Address propertyAddress;

    /** Geocoded coordinates of the property address. */
    private GeoPoint propertyCoords;

    // ── Scheduling ────────────────────────────────────────────────────────────

    /** Earliest acceptable start time; null means ASAP. */
    private Timestamp startWindowEarliest;

    /** Latest acceptable start time; null means no upper bound. */
    private Timestamp startWindowLatest;

    /** Optional instructions for the Worker (max 500 chars). */
    private String notesForWorker;

    // ── Images ────────────────────────────────────────────────────────────────

    /** Up to 5 images submitted by the Requester at request time. */
    private List<String> requestImageIds;

    /** Up to 5 images submitted by the Worker at completion. */
    private List<String> completionImageIds;

    /** Up to 5 images submitted by the Requester when disputing. */
    private List<String> disputeImageIds;

    // ── Preferences ───────────────────────────────────────────────────────────

    /**
     * When true, only "personal" designation Workers are eligible.
     * Dispatcher Workers are excluded from the offer round.
     */
    private boolean personalWorkerOnly;

    // ── Negotiated Marketplace (v1.1) ─────────────────────────────────────────

    /**
     * Price (in cents) proposed by the Requester when posting the job.
     * YSM recommends a price; the Requester may change it.
     */
    private Integer postedPriceCents;

    /**
     * Price (in cents) agreed by both parties after negotiation.
     * Set when OfferService records a mutual acceptance.
     */
    private Integer agreedPriceCents;

    /** UID of the Worker who agreed to the final negotiated price. */
    private String agreedWorkerId;

    /** Workers the Requester has rejected from this job (job-by-job blocking). */
    private List<String> rejectedWorkerIds;

    /**
     * Hours the Requester has to approve or dispute after the Worker posts completion.
     * Default is 2; set when the Requester deposits escrow and acknowledges the window.
     */
    private int approvalWindowHours;

    /** When the Requester explicitly acknowledged the approval window at escrow deposit time. */
    private Timestamp approvalWindowAcknowledgedAt;

    private Timestamp postedAt;
    private Timestamp agreedAt;
    private Timestamp pendingApprovalAt;
    private Timestamp approvedAt;

    // ── Pricing (set when Requester deposits escrow; locked at ESCROW_HELD) ──

    /** Worker's applicable tier price in CAD; null until escrow deposited. */
    private Double tierPriceCAD;

    /** Ontario HST (13%); 0 if Worker is not HST-registered. */
    private Double hstAmountCAD;

    /** tierPriceCAD + hstAmountCAD; the total the Requester pays. */
    private Double totalAmountCAD;

    /** Commission rate applied at disbursement: 0.0, 0.08, or 0.15. */
    private Double commissionRateApplied;

    /** Worker's net payout in CAD after commission deduction. */
    private Double workerPayoutCAD;

    // ── Payment ───────────────────────────────────────────────────────────────

    private String stripePaymentIntentId;

    /**
     * Stripe PaymentIntent client secret — returned to the client for
     * Stripe.js confirmation.  Never logged.
     */
    private String stripePaymentIntentClientSecret;

    /** Stripe Transfer ID created when the Worker is paid out at RELEASED state. */
    private String stripeTransferId;

    /**
     * Stripe Refund ID created on a SPLIT or REFUNDED dispute resolution.
     * Null for full-release outcomes.
     */
    private String stripeRefundId;

    private Timestamp escrowDepositedAt;

    /** 30 minutes after Worker acceptance — deposit must arrive by this time. */
    private Timestamp escrowDepositExpiry;

    // ── Lifecycle timestamps ──────────────────────────────────────────────────

    /** @deprecated Replaced by postedAt in v1.1. Retained for Firestore read compatibility. */
    @Deprecated
    private Timestamp requestedAt;

    /** @deprecated Sequential dispatch retired in v1.1. Retained for Firestore read compatibility. */
    @Deprecated
    private Timestamp offeredAt;

    /** @deprecated Replaced by agreedAt in v1.1. Retained for Firestore read compatibility. */
    @Deprecated
    private Timestamp acceptedAt;

    private Timestamp depositReceivedAt;

    /** @deprecated Replaced by escrowDepositedAt in v1.1. Retained for Firestore read compatibility. */
    @Deprecated
    private Timestamp confirmedAt;

    private Timestamp inProgressAt;
    private Timestamp completedAt;

    /** 4 hours after completedAt — auto-release fires if Requester hasn't acted. */
    private Timestamp autoReleaseAt;

    private Timestamp releasedAt;
    private Timestamp refundedAt;
    private Timestamp cancelledAt;

    /** "requester" | "worker" | "system" */
    private String cancelledBy;

    // ── Cancellation ─────────────────────────────────────────────────────────

    /** $10 CAD fee charged if cancelled after CONFIRMED but before IN_PROGRESS. */
    private Double cancellationFeeCAD;

    // ── Cannot Complete ───────────────────────────────────────────────────────

    /**
     * Reason Worker submitted Cannot Complete.
     * One of: "equipment_failure" | "safety_concern" | "access_blocked" |
     *         "weather" | "other"
     */
    private String cannotCompleteReason;

    private String cannotCompleteNote;
    private Timestamp cannotCompleteAt;

    /** 24 hours after Cannot Complete — admin resolution deadline. */
    private Timestamp incompleteResolutionDeadline;

    // ── Dispute ───────────────────────────────────────────────────────────────

    private Timestamp disputeInitiatedAt;

    /** Firestore ID of the Dispute document, set when a dispute is opened. */
    private String disputeId;

    private String disputeReason;
    private String disputeDescription;

    /** "release" | "refund" | "split" — set by admin on resolution. */
    private String disputeResolution;

    private Timestamp disputeResolvedAt;
    private String disputeWorkerNotes;

    // ── Worker dispatch ───────────────────────────────────────────────────────

    /**
     * Workers who have already been contacted for this job (declined or timed out).
     * Used to exclude them from future rounds.
     */
    private List<String> contactedWorkerIds;

    /** Which round of simultaneous offers this is (starts at 1). */
    private int offerRound;

    /** Workers who currently hold active offers in this round. */
    private List<String> simultaneousOfferWorkerIds;

    /** Offer expiry timestamp — 10 minutes from offeredAt. */
    private Timestamp offerExpiry;

    /**
     * Ordered list of Worker UIDs produced by MatchingService (P1-09).
     * Workers are ranked: rating DESC, distance ASC.  Max 20 entries.
     * Empty until matching completes (async after job creation).
     */
    private List<String> matchedWorkerIds;

    /**
     * Worker UIDs explicitly selected by the Requester at posting time.
     * When non-empty, only these Workers receive offers (bypassing the matching algorithm).
     */
    private List<String> selectedWorkerIds;

    // ── Flags ─────────────────────────────────────────────────────────────────

    /** Should be 0 or 1 — irreversible after Cannot Complete is submitted. */
    private int cannotCompleteCountThisJob;

    /**
     * Set to {@code true} by {@link com.yosnowmow.service.FraudDetectionService}
     * when one or more fraud rules trigger before payout release.
     * Cleared to {@code false} when an Admin approves the associated fraud flag.
     */
    private boolean payoutPaused;

    // ── Timestamps ────────────────────────────────────────────────────────────

    private Timestamp createdAt;
    private Timestamp updatedAt;

    // ── Constructors ─────────────────────────────────────────────────────────

    /** Required by Firestore deserialisation. */
    public Job() {}

    // ── Getters & Setters ────────────────────────────────────────────────────

    public String getJobId() { return jobId; }
    public void setJobId(String jobId) { this.jobId = jobId; }

    public String getRequesterId() { return requesterId; }
    public void setRequesterId(String requesterId) { this.requesterId = requesterId; }

    public String getWorkerId() { return workerId; }
    public void setWorkerId(String workerId) { this.workerId = workerId; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public List<String> getScope() { return scope; }
    public void setScope(List<String> scope) { this.scope = scope; }

    public Address getPropertyAddress() { return propertyAddress; }
    public void setPropertyAddress(Address propertyAddress) { this.propertyAddress = propertyAddress; }

    public GeoPoint getPropertyCoords() { return propertyCoords; }
    public void setPropertyCoords(GeoPoint propertyCoords) { this.propertyCoords = propertyCoords; }

    public Timestamp getStartWindowEarliest() { return startWindowEarliest; }
    public void setStartWindowEarliest(Timestamp startWindowEarliest) { this.startWindowEarliest = startWindowEarliest; }

    public Timestamp getStartWindowLatest() { return startWindowLatest; }
    public void setStartWindowLatest(Timestamp startWindowLatest) { this.startWindowLatest = startWindowLatest; }

    public String getNotesForWorker() { return notesForWorker; }
    public void setNotesForWorker(String notesForWorker) { this.notesForWorker = notesForWorker; }

    public List<String> getRequestImageIds() { return requestImageIds; }
    public void setRequestImageIds(List<String> requestImageIds) { this.requestImageIds = requestImageIds; }

    public List<String> getCompletionImageIds() { return completionImageIds; }
    public void setCompletionImageIds(List<String> completionImageIds) { this.completionImageIds = completionImageIds; }

    public List<String> getDisputeImageIds() { return disputeImageIds; }
    public void setDisputeImageIds(List<String> disputeImageIds) { this.disputeImageIds = disputeImageIds; }

    public boolean isPersonalWorkerOnly() { return personalWorkerOnly; }
    public void setPersonalWorkerOnly(boolean personalWorkerOnly) { this.personalWorkerOnly = personalWorkerOnly; }

    public Integer getPostedPriceCents() { return postedPriceCents; }
    public void setPostedPriceCents(Integer postedPriceCents) { this.postedPriceCents = postedPriceCents; }

    public Integer getAgreedPriceCents() { return agreedPriceCents; }
    public void setAgreedPriceCents(Integer agreedPriceCents) { this.agreedPriceCents = agreedPriceCents; }

    public String getAgreedWorkerId() { return agreedWorkerId; }
    public void setAgreedWorkerId(String agreedWorkerId) { this.agreedWorkerId = agreedWorkerId; }

    public List<String> getRejectedWorkerIds() { return rejectedWorkerIds; }
    public void setRejectedWorkerIds(List<String> rejectedWorkerIds) { this.rejectedWorkerIds = rejectedWorkerIds; }

    public int getApprovalWindowHours() { return approvalWindowHours; }
    public void setApprovalWindowHours(int approvalWindowHours) { this.approvalWindowHours = approvalWindowHours; }

    public Timestamp getApprovalWindowAcknowledgedAt() { return approvalWindowAcknowledgedAt; }
    public void setApprovalWindowAcknowledgedAt(Timestamp t) { this.approvalWindowAcknowledgedAt = t; }

    public Timestamp getPostedAt() { return postedAt; }
    public void setPostedAt(Timestamp postedAt) { this.postedAt = postedAt; }

    public Timestamp getAgreedAt() { return agreedAt; }
    public void setAgreedAt(Timestamp agreedAt) { this.agreedAt = agreedAt; }

    public Timestamp getPendingApprovalAt() { return pendingApprovalAt; }
    public void setPendingApprovalAt(Timestamp pendingApprovalAt) { this.pendingApprovalAt = pendingApprovalAt; }

    public Timestamp getApprovedAt() { return approvedAt; }
    public void setApprovedAt(Timestamp approvedAt) { this.approvedAt = approvedAt; }

    public Double getTierPriceCAD() { return tierPriceCAD; }
    public void setTierPriceCAD(Double tierPriceCAD) { this.tierPriceCAD = tierPriceCAD; }

    public Double getHstAmountCAD() { return hstAmountCAD; }
    public void setHstAmountCAD(Double hstAmountCAD) { this.hstAmountCAD = hstAmountCAD; }

    public Double getTotalAmountCAD() { return totalAmountCAD; }
    public void setTotalAmountCAD(Double totalAmountCAD) { this.totalAmountCAD = totalAmountCAD; }

    public Double getCommissionRateApplied() { return commissionRateApplied; }
    public void setCommissionRateApplied(Double commissionRateApplied) { this.commissionRateApplied = commissionRateApplied; }

    public Double getWorkerPayoutCAD() { return workerPayoutCAD; }
    public void setWorkerPayoutCAD(Double workerPayoutCAD) { this.workerPayoutCAD = workerPayoutCAD; }

    public String getStripePaymentIntentId() { return stripePaymentIntentId; }
    public void setStripePaymentIntentId(String stripePaymentIntentId) { this.stripePaymentIntentId = stripePaymentIntentId; }

    public String getStripePaymentIntentClientSecret() { return stripePaymentIntentClientSecret; }
    public void setStripePaymentIntentClientSecret(String s) { this.stripePaymentIntentClientSecret = s; }

    public String getStripeTransferId() { return stripeTransferId; }
    public void setStripeTransferId(String stripeTransferId) { this.stripeTransferId = stripeTransferId; }

    public String getStripeRefundId() { return stripeRefundId; }
    public void setStripeRefundId(String stripeRefundId) { this.stripeRefundId = stripeRefundId; }

    public Timestamp getEscrowDepositedAt() { return escrowDepositedAt; }
    public void setEscrowDepositedAt(Timestamp escrowDepositedAt) { this.escrowDepositedAt = escrowDepositedAt; }

    public Timestamp getEscrowDepositExpiry() { return escrowDepositExpiry; }
    public void setEscrowDepositExpiry(Timestamp escrowDepositExpiry) { this.escrowDepositExpiry = escrowDepositExpiry; }

    public Timestamp getRequestedAt() { return requestedAt; }
    public void setRequestedAt(Timestamp requestedAt) { this.requestedAt = requestedAt; }

    public Timestamp getOfferedAt() { return offeredAt; }
    public void setOfferedAt(Timestamp offeredAt) { this.offeredAt = offeredAt; }

    public Timestamp getAcceptedAt() { return acceptedAt; }
    public void setAcceptedAt(Timestamp acceptedAt) { this.acceptedAt = acceptedAt; }

    public Timestamp getDepositReceivedAt() { return depositReceivedAt; }
    public void setDepositReceivedAt(Timestamp depositReceivedAt) { this.depositReceivedAt = depositReceivedAt; }

    public Timestamp getConfirmedAt() { return confirmedAt; }
    public void setConfirmedAt(Timestamp confirmedAt) { this.confirmedAt = confirmedAt; }

    public Timestamp getInProgressAt() { return inProgressAt; }
    public void setInProgressAt(Timestamp inProgressAt) { this.inProgressAt = inProgressAt; }

    public Timestamp getCompletedAt() { return completedAt; }
    public void setCompletedAt(Timestamp completedAt) { this.completedAt = completedAt; }

    public Timestamp getAutoReleaseAt() { return autoReleaseAt; }
    public void setAutoReleaseAt(Timestamp autoReleaseAt) { this.autoReleaseAt = autoReleaseAt; }

    public Timestamp getReleasedAt() { return releasedAt; }
    public void setReleasedAt(Timestamp releasedAt) { this.releasedAt = releasedAt; }

    public Timestamp getRefundedAt() { return refundedAt; }
    public void setRefundedAt(Timestamp refundedAt) { this.refundedAt = refundedAt; }

    public Timestamp getCancelledAt() { return cancelledAt; }
    public void setCancelledAt(Timestamp cancelledAt) { this.cancelledAt = cancelledAt; }

    public String getCancelledBy() { return cancelledBy; }
    public void setCancelledBy(String cancelledBy) { this.cancelledBy = cancelledBy; }

    public Double getCancellationFeeCAD() { return cancellationFeeCAD; }
    public void setCancellationFeeCAD(Double cancellationFeeCAD) { this.cancellationFeeCAD = cancellationFeeCAD; }

    public String getCannotCompleteReason() { return cannotCompleteReason; }
    public void setCannotCompleteReason(String cannotCompleteReason) { this.cannotCompleteReason = cannotCompleteReason; }

    public String getCannotCompleteNote() { return cannotCompleteNote; }
    public void setCannotCompleteNote(String cannotCompleteNote) { this.cannotCompleteNote = cannotCompleteNote; }

    public Timestamp getCannotCompleteAt() { return cannotCompleteAt; }
    public void setCannotCompleteAt(Timestamp cannotCompleteAt) { this.cannotCompleteAt = cannotCompleteAt; }

    public Timestamp getIncompleteResolutionDeadline() { return incompleteResolutionDeadline; }
    public void setIncompleteResolutionDeadline(Timestamp t) { this.incompleteResolutionDeadline = t; }

    public Timestamp getDisputeInitiatedAt() { return disputeInitiatedAt; }
    public void setDisputeInitiatedAt(Timestamp disputeInitiatedAt) { this.disputeInitiatedAt = disputeInitiatedAt; }

    public String getDisputeId() { return disputeId; }
    public void setDisputeId(String disputeId) { this.disputeId = disputeId; }

    public String getDisputeReason() { return disputeReason; }
    public void setDisputeReason(String disputeReason) { this.disputeReason = disputeReason; }

    public String getDisputeDescription() { return disputeDescription; }
    public void setDisputeDescription(String disputeDescription) { this.disputeDescription = disputeDescription; }

    public String getDisputeResolution() { return disputeResolution; }
    public void setDisputeResolution(String disputeResolution) { this.disputeResolution = disputeResolution; }

    public Timestamp getDisputeResolvedAt() { return disputeResolvedAt; }
    public void setDisputeResolvedAt(Timestamp disputeResolvedAt) { this.disputeResolvedAt = disputeResolvedAt; }

    public String getDisputeWorkerNotes() { return disputeWorkerNotes; }
    public void setDisputeWorkerNotes(String disputeWorkerNotes) { this.disputeWorkerNotes = disputeWorkerNotes; }

    public List<String> getContactedWorkerIds() { return contactedWorkerIds; }
    public void setContactedWorkerIds(List<String> contactedWorkerIds) { this.contactedWorkerIds = contactedWorkerIds; }

    public int getOfferRound() { return offerRound; }
    public void setOfferRound(int offerRound) { this.offerRound = offerRound; }

    public List<String> getSimultaneousOfferWorkerIds() { return simultaneousOfferWorkerIds; }
    public void setSimultaneousOfferWorkerIds(List<String> ids) { this.simultaneousOfferWorkerIds = ids; }

    public Timestamp getOfferExpiry() { return offerExpiry; }
    public void setOfferExpiry(Timestamp offerExpiry) { this.offerExpiry = offerExpiry; }

    public int getCannotCompleteCountThisJob() { return cannotCompleteCountThisJob; }
    public void setCannotCompleteCountThisJob(int cannotCompleteCountThisJob) { this.cannotCompleteCountThisJob = cannotCompleteCountThisJob; }

    public List<String> getMatchedWorkerIds() { return matchedWorkerIds; }
    public void setMatchedWorkerIds(List<String> matchedWorkerIds) { this.matchedWorkerIds = matchedWorkerIds; }

    public List<String> getSelectedWorkerIds() { return selectedWorkerIds; }
    public void setSelectedWorkerIds(List<String> selectedWorkerIds) { this.selectedWorkerIds = selectedWorkerIds; }

    public boolean isPayoutPaused() { return payoutPaused; }
    public void setPayoutPaused(boolean payoutPaused) { this.payoutPaused = payoutPaused; }

    public Timestamp getCreatedAt() { return createdAt; }
    public void setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }

    public Timestamp getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(Timestamp updatedAt) { this.updatedAt = updatedAt; }
}
